name: flutter_template
description: A Flutter Template to get started quickly
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  device_info: ^2.0.0
  dio: ^4.0.0
  firebase_core: ^1.6.0
  firebase_crashlytics: ^2.2.1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.0.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^4.1.0
  flutter_svg: ^0.22.0
  get_it: ^7.2.0
  icapps_architecture: ^0.4.2
  injectable: ^1.4.1
  json_annotation: ^4.1.0
  moor: ^4.2.1
  moor_db_viewer: ^4.4.0
  moor_inspector: ^0.3.1
  niddler_dart: ^1.0.0
  path: ^1.8.0
  path_provider: ^2.0.1
  pedantic: ^1.11.1
  provider: ^6.0.0
  retrofit: ^2.0.0-beta1
  scroll_when_needed: ^2.0.0
  shared_preferences: ^2.0.5
  sqlite3_flutter_libs: ^0.5.0

dev_dependencies:
  build_runner: ^2.1.1
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  icapps_license: ^2.0.0
  icapps_translations: ^4.4.1
  injectable_generator: ^1.5.0
  json_serializable: ^5.0.0
  mockito: ^5.0.15
  model_generator: ^5.1.1
  moor_generator: ^4.5.1
  retrofit_generator: ^2.0.1+1

dependency_overrides:
  meta: ^1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/api/
    - assets/fonts/
    - assets/fonts/open_sans/
    - assets/locale/
    - assets/images/
    - assets/images/icons/
    - assets/images/icons/android/
    - assets/images/icons/ios/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
